spring.application.name=carbon-track

# DB CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/carbon_track
spring.datasource.username=root
spring.datasource.password=root

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# FLYWAY CONFIG
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#jwt
jwt.secret=7wN6V9K2mP8xR4zT1fG5hJ3kL9qA2sD6Y8uI4oP7nM1bC5vX
jwt.expiration=86400000